version: '3.9'

services:
  nest-help-postgres:
#    postgis can work with geolocation
    image: postgis/postgis
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nest-help
    volumes:
      - nest-help-db:/var/lib/postgresql/nest-help

volumes:
  nest-help-db:

