export enum RegionEnum {
  VINNYTSIA = 'Vinnytsia Oblast',
  VOLYN = 'Volyn Oblast',
  DNIPRO = 'Dnipropetrovsk Oblast',
  DONETSK = 'Donetsk Oblast',
  ZHYTOMYR = 'Zhytomyr Oblast',
  ZAKARPATTIA = 'Zakarpattia Oblast',
  ZAPORIZHIA = 'Zaporizhia Oblast',
  IVANO_FRANKIVSK = 'Ivano-Frankivsk Oblast',
  KYIV = 'Kyiv Oblast',
  KIROVOHRAD = 'Kirovohrad Oblast',
  LUHANSK = 'Luhansk Oblast',
  LVIV = 'Lviv Oblast',
  MYKOLAIV = 'Mykolaiv Oblast',
  ODESA = 'Odesa Oblast',
  POLTAVA = 'Poltava Oblast',
  RIVNE = 'Rivne Oblast',
  SUMY = 'Sumy Oblast',
  TERNOPIL = 'Ternopil Oblast',
  KHARKIV = 'Kharkiv Oblast',
  KHMELNYTSKYI = 'Khmelnytskyi Oblast',
  CHERKASY = 'Cherkasy Oblast',
  CHERNIVTSI = 'Chernivtsi Oblast',
  CHERNIHIV = 'Chernihiv Oblast',
  CRIMEA = 'Autonomous Republic of Crimea',
  KYIV_CITY = 'Kyiv City',
}
